/**
 * Mock data for testing without database connection
 * Used when DATABASE_URL is not configured or DB is unavailable
 */

const categories = [
  { id: 1, name: 'Electronics', description: 'Electronic devices and accessories' },
  { id: 2, name: 'Books', description: 'Physical and digital books' },
  { id: 3, name: 'Clothing', description: 'Apparel and fashion items' },
  { id: 4, name: 'Home & Kitchen', description: 'Home appliances and kitchen items' },
  { id: 5, name: 'Sports', description: 'Sports equipment and accessories' },
];

const products = [
  {
    id: 1,
    name: 'Wireless Bluetooth Headphones',
    description: 'High-quality wireless headphones with noise cancellation',
    price: 79.99,
    stock_quantity: 150,
    category_id: 1,
    category_name: 'Electronics',
    primary_image: 'https://images.example.com/headphones-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 2,
    name: 'USB-C Charging Cable 3-Pack',
    description: 'Durable braided USB-C cables, 6ft length',
    price: 15.99,
    stock_quantity: 500,
    category_id: 1,
    category_name: 'Electronics',
    primary_image: 'https://images.example.com/usb-cable-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 3,
    name: 'Smart Watch Pro',
    description: 'Fitness tracker with heart rate monitor and GPS',
    price: 199.99,
    stock_quantity: 75,
    category_id: 1,
    category_name: 'Electronics',
    primary_image: 'https://images.example.com/smartwatch-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 4,
    name: 'The Art of Programming',
    description: 'Comprehensive guide to software development',
    price: 49.99,
    stock_quantity: 200,
    category_id: 2,
    category_name: 'Books',
    primary_image: 'https://images.example.com/book-programming-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 5,
    name: 'JavaScript: The Good Parts',
    description: 'Essential JavaScript programming concepts',
    price: 29.99,
    stock_quantity: 180,
    category_id: 2,
    category_name: 'Books',
    primary_image: 'https://images.example.com/book-js-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 6,
    name: 'Cotton T-Shirt Pack',
    description: 'Pack of 5 premium cotton t-shirts',
    price: 34.99,
    stock_quantity: 300,
    category_id: 3,
    category_name: 'Clothing',
    primary_image: 'https://images.example.com/tshirt-pack-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 7,
    name: 'Running Shoes Ultra',
    description: 'Lightweight running shoes with cushioned sole',
    price: 89.99,
    stock_quantity: 120,
    category_id: 5,
    category_name: 'Sports',
    primary_image: 'https://images.example.com/running-shoes-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 8,
    name: 'Stainless Steel Water Bottle',
    description: 'Insulated 32oz water bottle',
    price: 24.99,
    stock_quantity: 400,
    category_id: 4,
    category_name: 'Home & Kitchen',
    primary_image: 'https://images.example.com/water-bottle-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 9,
    name: 'Yoga Mat Premium',
    description: 'Non-slip exercise yoga mat, 6mm thick',
    price: 29.99,
    stock_quantity: 250,
    category_id: 5,
    category_name: 'Sports',
    primary_image: 'https://images.example.com/yoga-mat-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 10,
    name: 'Mechanical Keyboard RGB',
    description: 'Gaming keyboard with RGB backlight',
    price: 129.99,
    stock_quantity: 80,
    category_id: 1,
    category_name: 'Electronics',
    primary_image: 'https://images.example.com/keyboard-1.jpg',
    created_at: '2026-01-01T00:00:00.000Z',
    updated_at: '2026-01-01T00:00:00.000Z',
  },
];

const productImages = [
  { id: 1, product_id: 1, image_url: 'https://images.example.com/headphones-1.jpg', is_primary: true, display_order: 1 },
  { id: 2, product_id: 1, image_url: 'https://images.example.com/headphones-2.jpg', is_primary: false, display_order: 2 },
  { id: 3, product_id: 1, image_url: 'https://images.example.com/headphones-3.jpg', is_primary: false, display_order: 3 },
  { id: 4, product_id: 2, image_url: 'https://images.example.com/usb-cable-1.jpg', is_primary: true, display_order: 1 },
  { id: 5, product_id: 3, image_url: 'https://images.example.com/smartwatch-1.jpg', is_primary: true, display_order: 1 },
  { id: 6, product_id: 3, image_url: 'https://images.example.com/smartwatch-2.jpg', is_primary: false, display_order: 2 },
  { id: 7, product_id: 4, image_url: 'https://images.example.com/book-programming-1.jpg', is_primary: true, display_order: 1 },
  { id: 8, product_id: 5, image_url: 'https://images.example.com/book-js-1.jpg', is_primary: true, display_order: 1 },
  { id: 9, product_id: 6, image_url: 'https://images.example.com/tshirt-pack-1.jpg', is_primary: true, display_order: 1 },
  { id: 10, product_id: 6, image_url: 'https://images.example.com/tshirt-pack-2.jpg', is_primary: false, display_order: 2 },
  { id: 11, product_id: 7, image_url: 'https://images.example.com/running-shoes-1.jpg', is_primary: true, display_order: 1 },
  { id: 12, product_id: 7, image_url: 'https://images.example.com/running-shoes-2.jpg', is_primary: false, display_order: 2 },
  { id: 13, product_id: 8, image_url: 'https://images.example.com/water-bottle-1.jpg', is_primary: true, display_order: 1 },
  { id: 14, product_id: 9, image_url: 'https://images.example.com/yoga-mat-1.jpg', is_primary: true, display_order: 1 },
  { id: 15, product_id: 10, image_url: 'https://images.example.com/keyboard-1.jpg', is_primary: true, display_order: 1 },
  { id: 16, product_id: 10, image_url: 'https://images.example.com/keyboard-2.jpg', is_primary: false, display_order: 2 },
];

module.exports = {
  categories,
  products,
  productImages,
};
